### ISSUE TITLE
The dash can't download in IQIYI for TAIWAN，

### ISSUE THREAD

**Issue by daliali2088** [sohail0098/iqiyi-dl#2]
Hello， I try to download the dash in IQYI（taiwan），It cannot work.  
Is there anything that needs to be modified?

https://cache-video.iq.com/dash?tvid=7382833651071400&bid=600&vid=abe2c4788688b54418ebe6a4119bf1a5&src=01011021010010000000&vt=0&rs=1&uid=34014000015&ori=pcw&ps=0&k_uid=37738a93005c21cb090b7296c9ea9ed7&pt=0&d=0&s=&lid=1&slid=1&cf=2&ct=&authKey=5c07fe7b12dc30efaab6c4e7ac5ffa38&k_tag=1&ost=0&ppt=0&dfp=a04c11e1ff2a835971952a33f7cec722082fd6dad3db1102856df47e85f1b916fb&prio=%7B%22ff%22%3A%22f4v%22%2C%22code%22%3A2%7D&k_err_retries=0&up=&su=2&applang=zh_cn&sver=2&X-USER-MODE=ntw&qd_v=2&tm=1633768101776&qdy=a&qds=0&k_ft1=141287244169348&k_ft4=8196&k_ft5=1&bop=%7B%22version%22%3A%2210.0%22%2C%22dfp%22%3A%22a04c11e1ff2a835971952a33f7cec722082fd6dad3db1102856df47e85f1b916fb%22%7D&ut=100058&vf=48ea1bd00c08cbaa0b81cc83f3bfdc26

**Comment by sohail0098** [comment]
When I made the script, I was in my home country where iq Taiwan wasn't accessible. 
Judging by the response of the above URL, it should work just fine. 
I'll take a look later if iq TW opens up in this new place I am in.

**Comment by ali617768987** [comment]
> When I made the script, I was in my home country where iq Taiwan wasn't accessible. Judging by the response of the above URL, it should work just fine. I'll take a look later if iq TW opens up in this new place I am in.

Okay, thanks. I just used the （tanwan）vpn to open it.
