### ISSUE TITLE
Cannot mux all subs to video

### ISSUE THREAD

**Issue by davidjames146** [sohail0098/iqiyi-dl#4]
Hello,

I cannot mux subs on temp download folder on video ? Can you help me this ?

Thanks!

**Comment by sohail0098** [comment]
Hi there. 
Can you please fill me in on some more info? The script should be able to mux the subtitles automatically. It would then delete the temp folder as well. Can you provide any kind of logs or something? Or is this unrelated to the script in this repo?

**Comment by davidjames146** [comment]
Hi,
Thanks for reply, the first time i download this script on this repo is can
download and mux sub automatically but is a free user and can download only
720p quality. After I upgrade my account to VIP and download 1080p, I have
problem with that error; sometimes is can mux ok sometimes is not. I have
already add valid cookies for VIP movies and can download full movies but
subs is not mux after finish Merging Files.
Thanks!

Vào Th 5, 18 thg 11, 2021 lúc 23:52 Mohd Sohail Ahmed <
***@***.***> đã viết:

**Comment by sohail0098** [comment]
Hi there. 
If you can tell me the show/episode name/number or provide me with a link, I can check it out during my free time. 
For now, this isn't sufficient info for me to even make a guess about why the issue happened.

Another thing you can do is, if temp files aren't deleted, you can merge the mp4 and srt files manually using MKVToolnix GUI (or mkvmerge if you are familiar with the cli)

**Comment by davidjames146** [comment]
> Hi there. If you can tell me the show/episode name/number or provide me with a link, I can check it out during my free time. For now, this isn't sufficient info for me to even make a guess about why the issue happened.
> 
> Another thing you can do is, if temp files aren't deleted, you can merge the mp4 and srt files manually using MKVToolnix GUI (or mkvmerge if you are familiar with the cli)

Here, this is the example of video link i have download but no mux sub:  https://www.iq.com/play/chi-dau-tro-ve-2021-q9u1sp0w8o?lang=vi_vn
